#backend:
#  name: git-gateway
#  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
#local_backend: true

backend:
  name: github
  repo: esoyke/newjam # Path to your GitHub repository

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "page"
    label: "Page"
    folder: "content/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Steve Martin", "Richard Pryor", "George Carlin"]}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "body", widget: "markdown"}
  
  # can add multiple collection locations
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}    

  - name: "premium"
    label: "Premium Page"
    folder: "content/premium"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Steve Martin", "Richard Pryor", "George Carlin"]}
      - {label: "Date", name: "date", widget: "datetime"}